server:
  port: 8764

spring:
  application:
    name: apigatway



  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

      routes:
        - id: FIRSTLAYER
          uri: lb://firstlayer
          predicates:
            - Path=/**
      # - id: question-service
      #   uri: 
      #     lb://QUESTION-SERVICE
      #   predicates:
      #   - Path=/QUESTION-SERVICE/**


      # - id: quiz-service
      #   uri: 
      #     lb://quiz-service
      #   predicates:
      #   - Path=/quiz-service/**